language: android
android:
  components:
  - tools
  - platform-tools
  - extra
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-x86-android-26
  - sys-img-armeabi-v7a-android-17
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-28"
script:
- "./gradlew assemble -p kotlinlog"
notifications:
  email: false
  slack:
    rooms:
      - secure: LT4G9Rs+7UdGJBjRa1AjjSYA5jK3EER06JzVNDOQzBKaUklmXllblOPxMEtAcpq15+EQOGZHzf5tyAWk8qVJlRnAHl3vz3y4iN2Yxnm3+r4g+YjifcYKvU4Y7n5gaP2UDjB040mUots1vuS4xlSDkaRgAo2Qj373qC13D6a9KEXJsJwicICdYfa0rTlDrq810QAHklxDeFiariFzheqYmw91ipgzwuQPnMBcbmbYL3Q+EGti9nFWG09QqMKnHKGrgYkvVCn2mv+Ctn1+41hxyMYzbk4VRpKftOIXkX1gGnq6mvzmJnYWl+qm+rGASA0oIiCAnHUhOjpJNNmMa3HmJOZCFTWKevDi5r2kIP2dMHKMM+V88vnCXcENgnlmLMUuq2F/Acxc2Bh8ANeVythAN1mA+qaqxMjg+nSfqYrNOy00sb948wd1dEq0yQy6Qn98dmjinJkV5gWdKctm7drpcdyVLzbgEuf4TirUWWT/drICy/MYqCgCIHHWLvTu1KkuDerfic8wfwwY5HCVWa39yqiUp/2ZyLKdcImxjhrGompHeiNncxTPLnRAGj85m5k8MBDpVpwVhfxrSgNorRITFEhSlkSTAwxZ3Kdc8+1EOxqW/kyxc+WS/WOO7evwY2F6COZRAsdT+mnOPnFW8aWBPpdMKa/fV4hh6dAyb9B9/xo=
    on_success: always
    on_failure: always
